#!/usr/bin/env python3
"""
Free Energy Principle (FEP) Learner for KV-1

Implements brain-inspired learning based on FEP:
- Recognition Network: Bottom-up inference (observations → beliefs)
- Generative Network: Top-down prediction (beliefs → predictions)
- Latent Variables: Internal model representation
- Free Energy Minimization: Prediction error + model complexity
- Active Inference: Act to minimize future surprise

Key Insight: Intelligence = Minimizing prediction error
- Perception: Update beliefs to match reality
- Action: Change reality to match beliefs
- Learning: Improve model to reduce future errors

Based on Karl Friston's Free Energy Principle and predictive coding.
"""

import numpy as np
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple, Any
from enum import Enum
import time


class LatentType(Enum):
    """Types of latent variables in hierarchical model"""
    HIGH_LEVEL = "high_level"  # Abstract concepts (domain, goal)
    MID_LEVEL = "mid_level"  # Structure (math type, approach)
    LOW_LEVEL = "low_level"  # Specific (parameters, details)


@dataclass
class LatentVariable:
    """
    Latent variable in internal model.

    These are the HIDDEN CAUSES that generate observations.
    Not directly observed, but inferred by recognition network.
    """
    name: str
    level: LatentType
    value: Any  # Could be string, number, distribution, etc.
    confidence: float  # 0-1, how certain we are

    # For continuous latents
    mean: Optional[float] = None
    variance: Optional[float] = None

    def __repr__(self):
        if self.mean is not None:
            return f"{self.name}={self.mean:.2f}±{np.sqrt(self.variance):.2f} (conf: {self.confidence:.2f})"
        else:
            return f"{self.name}={self.value} (conf: {self.confidence:.2f})"


@dataclass
class InternalModel:
    """
    Internal model = Set of latent variables representing beliefs.

    This is what the brain/AI "thinks" is causing observations.
    Hierarchical structure: high-level → mid-level → low-level
    """
    latents: Dict[str, LatentVariable] = field(default_factory=dict)

    # Free energy components
    prediction_error: float = 0.0  # How well predictions match reality
    complexity: float = 0.0  # How complex/unusual is this model

    @property
    def free_energy(self) -> float:
        """
        Total free energy = Prediction Error + Complexity

        Goal: Minimize this!
        """
        return self.prediction_error + self.complexity

    def add_latent(self, latent: LatentVariable):
        """Add latent variable to model"""
        self.latents[latent.name] = latent

    def get(self, name: str) -> Optional[LatentVariable]:
        """Get latent by name"""
        return self.latents.get(name)

    def to_dict(self) -> dict:
        """Serialize"""
        return {
            'latents': {name: repr(lat) for name, lat in self.latents.items()},
            'prediction_error': self.prediction_error,
            'complexity': self.complexity,
            'free_energy': self.free_energy
        }


@dataclass
class Observation:
    """
    Observation = Sensory input / data

    What we actually observe/measure in the world.
    """
    data: Any
    timestamp: float = field(default_factory=time.time)
    confidence: float = 1.0  # Sensory reliability

    def __repr__(self):
        return f"Obs({self.data}, conf: {self.confidence:.2f})"


@dataclass
class Prediction:
    """
    Prediction generated by generative model.

    What we EXPECT to observe given our beliefs.
    """
    predicted_data: Any
    confidence: float
    source_latents: List[str]  # Which latents generated this

    def __repr__(self):
        return f"Pred({self.predicted_data}, conf: {self.confidence:.2f})"


class RecognitionNetwork:
    """
    Recognition Network = Bottom-up inference.

    Takes observations → Infers latent causes
    "What's causing what I observe?"

    In brain: Feedforward connections (sensory → cortex)
    In transformers: Encoder
    In VAE: Encoder network
    """

    def __init__(self):
        # Store observed patterns for learning
        self.observed_patterns: List[Tuple[Any, InternalModel]] = []

    def infer_latents(
        self,
        observation: Observation,
        prior_model: Optional[InternalModel] = None
    ) -> InternalModel:
        """
        Infer latent causes from observation.

        This is PERCEPTION: Figure out what's causing sensory input.

        Args:
            observation: What we observe
            prior_model: Previous beliefs (if any)

        Returns:
            Internal model with inferred latents
        """
        model = InternalModel()

        # Extract features from observation
        obs_data = str(observation.data).lower()

        # High-level inference: What domain?
        domain = self._infer_domain(obs_data)
        model.add_latent(LatentVariable(
            name="domain",
            level=LatentType.HIGH_LEVEL,
            value=domain,
            confidence=0.7
        ))

        # Mid-level inference: What structure?
        structure = self._infer_structure(obs_data, domain)
        model.add_latent(LatentVariable(
            name="structure",
            level=LatentType.MID_LEVEL,
            value=structure,
            confidence=0.6
        ))

        # Low-level inference: Specific parameters
        # (Would be more sophisticated in full implementation)

        # Compute complexity
        model.complexity = self._compute_complexity(model)

        return model

    def _infer_domain(self, obs_data: str) -> str:
        """Infer domain from observation (simplified)"""
        keywords = {
            'physics': ['force', 'energy', 'velocity', 'motion', 'mass'],
            'mathematics': ['equation', 'derivative', 'integral', 'function', 'theorem'],
            'biology': ['population', 'species', 'evolution', 'cell', 'growth'],
            'economics': ['price', 'cost', 'market', 'demand', 'profit'],
            'politics': ['vote', 'election', 'coalition', 'policy', 'government']
        }

        scores = {}
        for domain, kws in keywords.items():
            score = sum(1 for kw in kws if kw in obs_data)
            if score > 0:
                scores[domain] = score

        if scores:
            return max(scores.items(), key=lambda x: x[1])[0]
        else:
            return 'unknown'

    def _infer_structure(self, obs_data: str, domain: str) -> str:
        """Infer mathematical structure (simplified)"""
        if any(kw in obs_data for kw in ['change', 'rate', 'derivative', 'dynamics']):
            return 'differential_equations'
        elif any(kw in obs_data for kw in ['maximize', 'minimize', 'optimal', 'best']):
            return 'optimization'
        elif any(kw in obs_data for kw in ['strategy', 'game', 'player', 'equilibrium']):
            return 'game_theory'
        elif any(kw in obs_data for kw in ['network', 'graph', 'connected', 'node']):
            return 'graph_theory'
        else:
            return 'unknown'

    def _compute_complexity(self, model: InternalModel) -> float:
        """
        Compute model complexity (KL divergence in full implementation).

        How unusual/complex is this model compared to prior?

        Simple heuristic: Rare combinations = high complexity
        """
        # In full implementation, would compute KL divergence from prior
        # Here: Simple heuristic based on domain-structure combination

        domain = model.get('domain')
        structure = model.get('structure')

        if not domain or not structure:
            return 0.5

        # Common combinations = low complexity
        common_pairs = {
            ('physics', 'differential_equations'): 0.1,
            ('mathematics', 'optimization'): 0.2,
            ('economics', 'optimization'): 0.15,
            ('biology', 'differential_equations'): 0.2,
        }

        pair = (domain.value, structure.value)
        complexity = common_pairs.get(pair, 0.7)  # Unusual = high complexity

        return complexity


class GenerativeNetwork:
    """
    Generative Network = Top-down prediction.

    Takes latent beliefs → Generates predictions
    "Given what I believe, what should I observe?"

    In brain: Feedback connections (cortex → sensory)
    In transformers: Decoder
    In VAE: Decoder network
    """

    def __init__(self):
        # Store generative models for different latent configurations
        self.generative_models: Dict[str, Any] = {}

    def generate_predictions(
        self,
        model: InternalModel
    ) -> List[Prediction]:
        """
        Generate predictions from internal model.

        This is top-down PREDICTION: What should I observe?

        Args:
            model: Internal model (latent variables)

        Returns:
            List of predictions about observables
        """
        predictions = []

        domain = model.get('domain')
        structure = model.get('structure')

        if not domain or not structure:
            return predictions

        # Generate domain-specific predictions
        if domain.value == 'physics':
            predictions.append(Prediction(
                predicted_data=f"Physical system will exhibit {structure.value} behavior",
                confidence=domain.confidence * structure.confidence,
                source_latents=['domain', 'structure']
            ))

        elif domain.value == 'mathematics':
            predictions.append(Prediction(
                predicted_data=f"Mathematical problem requires {structure.value}",
                confidence=domain.confidence * structure.confidence,
                source_latents=['domain', 'structure']
            ))

        elif domain.value == 'biology':
            predictions.append(Prediction(
                predicted_data=f"Biological system follows {structure.value}",
                confidence=domain.confidence * structure.confidence,
                source_latents=['domain', 'structure']
            ))

        # More predictions based on structure
        if structure.value == 'differential_equations':
            predictions.append(Prediction(
                predicted_data="Will observe time-dependent changes",
                confidence=structure.confidence,
                source_latents=['structure']
            ))

        elif structure.value == 'optimization':
            predictions.append(Prediction(
                predicted_data="Will need to find maximum or minimum",
                confidence=structure.confidence,
                source_latents=['structure']
            ))

        return predictions

    def sample_from_model(
        self,
        model: InternalModel
    ) -> Any:
        """
        Sample possible observations from generative model.

        This is IMAGINATION: What could I observe?
        """
        # In full implementation, would sample from learned distribution
        # Here: Return most likely observation based on latents

        domain = model.get('domain')
        structure = model.get('structure')

        if domain and structure:
            return f"Sample observation: {domain.value} problem with {structure.value}"
        else:
            return "No clear observation expected"


class FEPLearner:
    """
    Free Energy Principle Learner.

    Combines Recognition + Generative networks to minimize free energy.

    Process:
    1. Observe data
    2. Recognition: Infer latent causes
    3. Generative: Predict what should happen
    4. Compare: Compute prediction error
    5. Update: Minimize free energy

    Two ways to minimize:
    A) Update beliefs (perception/learning)
    B) Take action (active inference)
    """

    def __init__(self):
        self.recognition = RecognitionNetwork()
        self.generative = GenerativeNetwork()

        # Current internal model
        self.current_model: Optional[InternalModel] = None

        # Learning history
        self.history: List[Dict] = []

    def process_observation(
        self,
        observation: Observation,
        ground_truth: Optional[Any] = None
    ) -> Dict:
        """
        Full FEP cycle: Observe → Infer → Predict → Evaluate → Update

        Args:
            observation: What we observe
            ground_truth: Actual outcome (if known) for computing error

        Returns:
            Dict with model, predictions, errors
        """
        # Step 1: Recognition - Infer latent causes
        inferred_model = self.recognition.infer_latents(
            observation,
            prior_model=self.current_model
        )

        # Step 2: Generative - Make predictions
        predictions = self.generative.generate_predictions(inferred_model)

        # Step 3: Compute prediction error
        if ground_truth is not None:
            pred_error = self._compute_prediction_error(
                predictions,
                ground_truth
            )
            inferred_model.prediction_error = pred_error

        # Step 4: Compute free energy
        free_energy = inferred_model.free_energy

        # Step 5: Decide whether to update model
        should_update = self._should_update_model(inferred_model)

        if should_update:
            # Update current model (learning!)
            self.current_model = inferred_model

        # Log to history
        result = {
            'observation': repr(observation),
            'model': inferred_model.to_dict(),
            'predictions': [repr(p) for p in predictions],
            'free_energy': free_energy,
            'updated': should_update,
            'timestamp': time.time()
        }

        self.history.append(result)

        return result

    def _compute_prediction_error(
        self,
        predictions: List[Prediction],
        ground_truth: Any
    ) -> float:
        """
        Compute prediction error = surprise.

        How different are predictions from reality?
        """
        if not predictions:
            return 1.0  # Maximum surprise

        # Simple heuristic: Check if any prediction matches ground_truth
        ground_truth_str = str(ground_truth).lower()

        for pred in predictions:
            pred_str = str(pred.predicted_data).lower()

            # Check overlap
            pred_words = set(pred_str.split())
            truth_words = set(ground_truth_str.split())

            overlap = len(pred_words & truth_words)
            total = len(pred_words | truth_words)

            if total > 0:
                match = overlap / total
                if match > 0.3:  # Some match
                    return 0.5 * (1 - match)  # Low error if good match

        return 0.9  # High error if no match

    def _should_update_model(self, new_model: InternalModel) -> bool:
        """
        Decide whether to update beliefs.

        Update if:
        - New model has lower free energy
        - Or no current model exists
        """
        if self.current_model is None:
            return True

        # Update if new model is better (lower free energy)
        return new_model.free_energy < self.current_model.free_energy

    def active_inference(
        self,
        goal: str
    ) -> str:
        """
        Active inference: Choose action to minimize future free energy.

        Instead of updating beliefs to match reality,
        ACT to make reality match beliefs!

        Args:
            goal: What we want to achieve

        Returns:
            Suggested action
        """
        # Predict: What would achieve goal?
        goal_obs = Observation(data=goal)
        goal_model = self.recognition.infer_latents(goal_obs)

        # What action would reduce free energy?
        # (i.e., make predictions come true)

        domain = goal_model.get('domain')
        structure = goal_model.get('structure')

        if not domain or not structure:
            return "Explore to reduce uncertainty"

        # Suggest action based on model
        if structure.value == 'unknown':
            return f"Learn more about {domain.value} to reduce uncertainty"

        elif goal_model.complexity > 0.5:
            return f"This is unusual - explore {domain.value} + {structure.value}"

        else:
            return f"Apply {structure.value} to solve {domain.value} problem"

    def get_summary(self) -> Dict:
        """Get learning summary"""
        if not self.history:
            return {'message': 'No learning history yet'}

        return {
            'total_observations': len(self.history),
            'current_model': self.current_model.to_dict() if self.current_model else None,
            'average_free_energy': np.mean([h['free_energy'] for h in self.history]),
            'learning_trend': 'decreasing' if self._is_decreasing() else 'stable'
        }

    def _is_decreasing(self) -> bool:
        """Check if free energy is decreasing (learning progress)"""
        if len(self.history) < 2:
            return False

        recent = [h['free_energy'] for h in self.history[-10:]]
        return recent[-1] < recent[0]


def demo_fep():
    """Demonstrate FEP learning"""
    print("="*70)
    print("FREE ENERGY PRINCIPLE LEARNER - Demo")
    print("="*70)

    learner = FEPLearner()

    # Sequence of observations
    observations = [
        ("How does velocity change over time?", "Physics - differential equations"),
        ("Find the maximum profit given cost function", "Economics - optimization"),
        ("Population growth in limited environment", "Biology - differential equations"),
        ("What voting system is most fair?", "Politics - game theory"),
    ]

    print("\n[Learning Sequence]\n")

    for obs_text, ground_truth in observations:
        print(f"Observation: {obs_text}")

        obs = Observation(data=obs_text)
        result = learner.process_observation(obs, ground_truth=ground_truth)

        print(f"  Domain: {result['model']['latents'].get('domain', 'unknown')}")
        print(f"  Structure: {result['model']['latents'].get('structure', 'unknown')}")
        print(f"  Free Energy: {result['free_energy']:.3f}")
        print(f"  Model Updated: {'✓' if result['updated'] else '✗'}")
        print()

    # Active inference
    print("\n[Active Inference]")
    goal = "Learn about epidemic spread"
    action = learner.active_inference(goal)
    print(f"Goal: {goal}")
    print(f"Suggested Action: {action}")

    # Summary
    print("\n[Learning Summary]")
    summary = learner.get_summary()
    for key, value in summary.items():
        print(f"  {key}: {value}")

    print("\n" + "="*70)


if __name__ == "__main__":
    demo_fep()
